apiVersion: apps/v1
kind: Deployment
metadata:
  name: grupo25
  namespace: thymeleaf
spec:
  selector:
    matchLabels:
      app: grupo25
  replicas: 1
  template:
    metadata:
      labels:
         app: grupo25
    spec:
      imagePullSecrets:
         - name: github-secret
      containers:
         - name: test
           image: localhost:5000/grupo_2_5:latest
           ports:
              - containerPort: 8080
           env:
              - name: db_host2
                value: "190.146.2.119"
              - name: db_port2
                value: "4407"
              - name: db_database2
                value: "grupo_2_5"
              - name: db_username2
                value: "grupo_2_5"
              - name: db_password2
                value: "grupo_2_5"
---
apiVersion: v1
kind: Service
metadata:
  name: grupo25
  namespace: thymeleaf
spec:
#  type: NodePort
  selector:
    app: grupo25
  ports:
    - protocol: TCP
      port: 8080
#      nodePort: 30001
      targetPort: 8080